[package]
name = "cargo-swift-package"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
cargo_metadata = { version = "0.15", features = ["builder"] }
camino = "1.1"
yansi = "0.5"
fs-err = "2.9"
cargo-xcframework = { path = "../cargo-xcframework" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
fs_extra = "1.3.0"

[dev-dependencies]
tempfile = "3.3"
